In [1]:
import numpy as np

In [5]:
# Creating Array:

arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [6]:
arr2 = np.array([1,2,3,4,5, 'akg'])
arr2

array(['1', '2', '3', '4', '5', 'akg'], dtype='<U11')

In [7]:
print(type(arr1), type(arr2))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [8]:
# Creating 2D array:

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
print("Shape: ", arr.shape)
print("Dimention: ", arr.ndim)
print("Size:", arr.size)
print("Data type:", arr.dtype)

Shape:  (3, 3)
Dimention:  2
Size: 9
Data type: int32


In [11]:
# Creating nD array:

arr = np.array([1,2,3,4,5,6,7,8,9], ndmin=5)

print(arr)
print()
print("Shape: ", arr.shape)
print("Dimention: ", arr.ndim)
print("Size:", arr.size)
print("Data type:", arr.dtype)

[[[[[1 2 3 4 5 6 7 8 9]]]]]

Shape:  (1, 1, 1, 1, 9)
Dimention:  5
Size: 9
Data type: int32


In [12]:
# Creating & rehaping array:

arr = np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
# array iteration:

arr = np.arange(1,13).reshape(3,4)
lst = [j for i in arr for j in i]
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [15]:
# Array Splitting:

arr = np.arange(1,13).reshape(3,4)
np.array_split(arr, 3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [16]:
# Search an Element in an array:

arr = np.arange(1,25).reshape(4,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [23]:
index_position = np.where(arr == 16)
index_position

(array([2], dtype=int64), array([3], dtype=int64))

In [24]:
# Sort the array:

arr = np.array([11,1,22,3,9,13,8,4,5,6,7,10])
arr

array([11,  1, 22,  3,  9, 13,  8,  4,  5,  6,  7, 10])

In [26]:
sorted(arr)

[1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 22]

In [30]:
# Filtering:

# remove duplicates from array:
arr = np.array([1,2,5,8,1,9,10,12,2,3,4,5,11,2,4,7,9,10,12])
new_ = []

for i in arr:
    if i not in new_:
        new_.append(i)
        
np.array(new_)

array([ 1,  2,  5,  8,  9, 10, 12,  3,  4, 11,  7])

In [32]:
# Slicing Array:

arr = np.arange(1,25).reshape(4,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [33]:
arr[1:3, 2:5]

array([[ 9, 10, 11],
       [15, 16, 17]])

In [35]:
# 1D Array Concatination:

ar1 = np.array([1,2,3,4,5,6])
ar2 = np.array([10,11,12,13])
ar3 = np.array([21,22,23,24,25])


np.concatenate((ar1, ar2, ar3))

array([ 1,  2,  3,  4,  5,  6, 10, 11, 12, 13, 21, 22, 23, 24, 25])

In [36]:
# 2D Array Concatination:

ar1 = np.array([
    [1,2,3],
    [4,5,6]
])

ar2 = np.array([
    [10,11,12],
    [20,21,22]
])

np.concatenate((ar1, ar2), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12],
       [20, 21, 22]])

In [37]:
np.concatenate((ar1, ar2), axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 20, 21, 22]])

In [38]:
np.stack((ar1, ar2), axis=0)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [20, 21, 22]]])

In [39]:
np.stack((ar1, ar2), axis=1)

array([[[ 1,  2,  3],
        [10, 11, 12]],

       [[ 4,  5,  6],
        [20, 21, 22]]])

In [40]:
# Shallow Copy:

arr = np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
arr1 = arr
arr1[1][2] = 700

print("old array: \n", arr)
print()
print("new array: \n", arr1)

old array: 
 [[  1   2   3   4]
 [  5   6 700   8]
 [  9  10  11  12]]

new array: 
 [[  1   2   3   4]
 [  5   6 700   8]
 [  9  10  11  12]]


In [43]:
# Deep Copy:

arr = np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
arr2 = np.array(arr, copy=True)
arr2[1][2] =700

print("old array: \n", arr)
print()
print("new array: \n", arr2)

old array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

new array: 
 [[  1   2   3   4]
 [  5   6 700   8]
 [  9  10  11  12]]


In [48]:
# Random:

[np.random.rand(), np.random.rand(), np.random.rand(), np.random.rand()] # range 0 to 1

[0.7530799529968624,
 0.02626756145803022,
 0.6945633430261684,
 0.35322780730815306]

In [50]:
np.random.rand(3,4) # range 0 to 1

array([[0.80023622, 0.2766478 , 0.23358186, 0.82448784],
       [0.25481836, 0.73816526, 0.40876901, 0.62531081],
       [0.46725488, 0.2196243 , 0.72601025, 0.12522305]])

In [51]:
np.random.randn(2,3) # range 1 to -1

array([[ 0.33961986, -0.22288516, -0.17457066],
       [-1.09846051, -0.24395099, -1.32460654]])

In [52]:
np.random.randint(low=1, high=10, size=(3,5))

array([[2, 3, 4, 4, 1],
       [1, 8, 2, 3, 7],
       [9, 6, 8, 2, 8]])

In [53]:
np.random.random_sample((5,))

array([0.74163043, 0.41865434, 0.78872387, 0.08810826, 0.13482831])

In [54]:
np.random.random_sample((5,3))

array([[0.53803094, 0.71016988, 0.85965268],
       [0.32786992, 0.97219561, 0.0396637 ],
       [0.91686283, 0.61125933, 0.32750414],
       [0.48687794, 0.81448059, 0.05962089],
       [0.6401139 , 0.75047799, 0.03502312]])

In [55]:
np.random.ranf((3,5))

array([[0.97191713, 0.17190779, 0.29462144, 0.72887287, 0.06177733],
       [0.359396  , 0.65924543, 0.57189503, 0.3963496 , 0.9224699 ],
       [0.49947407, 0.15360513, 0.35676703, 0.02419751, 0.59490653]])

In [56]:
np.random.rayleigh(21, size=(3,4))

array([[49.72826671, 23.07235638, 27.28296274, 66.70397227],
       [35.15708768, 38.73003174, 24.13827239, 22.11464035],
       [15.36032503, 78.94506564, 25.68703393, 43.72077005]])

In [57]:
np.random.random_integers(1,13, size=(3,4))

C:\Users\Dibyendu\AppData\Local\Temp/ipykernel_12640/1660218705.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 13 + 1) instead
  np.random.random_integers(1,13, size=(3,4))


array([[ 9,  5, 10,  9],
       [ 1,  2, 12,  3],
       [ 5,  6, 10,  7]])

In [58]:
arr = np.random.randint(1,10, size=(24,)).reshape(4,6)
arr

array([[8, 8, 3, 7, 9, 9],
       [5, 6, 4, 5, 6, 4],
       [2, 2, 5, 9, 7, 5],
       [1, 1, 6, 7, 6, 4]])

In [59]:
print("Shape: ", arr.shape)
print("Dimention: ", arr.ndim)
print("Size:", arr.size)
print("Data type:", arr.dtype)

Shape:  (4, 6)
Dimention:  2
Size: 24
Data type: int32


In [62]:
# Creating Matrix:

arr = np.random.randint(1,8, size=(12,)).reshape(3,4)
mat = np.matrix(arr)
mat

matrix([[7, 7, 2, 3],
        [6, 7, 1, 5],
        [1, 7, 2, 3]])

In [64]:
print("Type:", type(mat))
print("Shape: ", mat.shape)
print("Dimention: ", mat.ndim)
print("Size:", mat.size)
print("Data type:", mat.dtype)

Type: <class 'numpy.matrix'>
Shape:  (3, 4)
Dimention:  2
Size: 12
Data type: int32


In [66]:
# Linespace:

np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [67]:
np.linspace(1,10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [69]:
np.linspace(1,10, 6).reshape(3,2)

array([[ 1. ,  2.8],
       [ 4.6,  6.4],
       [ 8.2, 10. ]])

In [70]:
# Ones:

np.ones(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [71]:
# Zeros:

np.zeros(shape=(3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
# Creating Diagonal Element:

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [73]:
# Extracting Diagonal Elements:

arr = np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [77]:
print("k=0  :", np.diag(arr, k=0))
print("k=1  :", np.diag(arr, k=1))
print("k=2  :", np.diag(arr, k=2))
print("k=-1 :", np.diag(arr, k=-1))
print("k=-2 :", np.diag(arr, k=-2))

k=0  : [ 1  6 11]
k=1  : [ 2  7 12]
k=2  : [3 8]
k=-1 : [ 5 10]
k=-2 : [9]


In [78]:
# create a array where diagonal elemet is [1,2,3,4]

np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [79]:
# Create a Triangle array:

np.tri(4,4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [80]:
np.tri(4, 4, k=1)

array([[1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [85]:
# Uppen Triangle & Lower Triangle:

arr = np.arange(1,13).reshape(3,4)
l_ = np.tril(arr)
u_ = np.triu(arr)

print("Original Array: \n", arr, '\n')
print("Lower Triangle: \n", l_, '\n')
print("Upper Triangle: \n", u_)

Original Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

Lower Triangle: 
 [[ 1  0  0  0]
 [ 5  6  0  0]
 [ 9 10 11  0]] 

Upper Triangle: 
 [[ 1  2  3  4]
 [ 0  6  7  8]
 [ 0  0 11 12]]


In [91]:
# Matrix:

mat = np.matrix(np.linspace(1,12,24, dtype=int).reshape(6,4))
mat

matrix([[ 1,  1,  1,  2],
        [ 2,  3,  3,  4],
        [ 4,  5,  5,  6],
        [ 6,  7,  7,  8],
        [ 8,  9,  9, 10],
        [10, 11, 11, 12]])

In [92]:
mat >= 5

matrix([[False, False, False, False],
        [False, False, False, False],
        [False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [94]:
mat[mat > 5]

matrix([[ 6,  6,  7,  7,  8,  8,  9,  9, 10, 10, 11, 11, 12]])

In [95]:
# Get Maximum & Minimum Value:

max_ = mat.max()
min_ = mat.min()

print("max: ", max_)
print("min: ", min_)

max:  12
min:  1


In [98]:
# argmax(): The numpy.argmax() function returns indices of the max element of the array in a particular axis.

print(mat.argmax(axis=0), '\n')
print(mat.argmax(axis=1))

[[5 5 5 5]] 

[[3]
 [3]
 [3]
 [3]
 [3]
 [3]]


In [101]:
# Broadcasting : (elements by element operation is called broadcasting)


ones = np.ones(shape=(3,4))
zeros = np.zeros(shape=(3,4))

ones + zeros + 11

array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [12., 12., 12., 12.]])

In [102]:
# Array Multiplications:


ar1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

ar2 = np.array([
    [1,2,3],
    [1,1,1],
    [2,3,1]
])

ar3 = np.zeros(shape=(3,3))
ar4 = np.ones(shape=(3,3))

In [103]:
ar1 * ar2

array([[ 1,  4,  9],
       [ 4,  5,  6],
       [14, 24,  9]])

In [104]:
ar1 @ ar2 # it's array multiplications

array([[ 9, 13,  8],
       [21, 31, 23],
       [33, 49, 38]])

In [105]:
ar1 + ar2 + ar3 + ar4

array([[ 3.,  5.,  7.],
       [ 6.,  7.,  8.],
       [10., 12., 11.]])

In [110]:
# Array Transpose:

arr = np.random.randint(1,12, size=(2,4))

print("Original Array: \n", arr, '\n')
print("Array Transpose: \n", arr.T)

Original Array: 
 [[ 5  2  7  5]
 [10  5 10  1]] 

Array Transpose: 
 [[ 5 10]
 [ 2  5]
 [ 7 10]
 [ 5  1]]


In [111]:
# Numpy from function:

np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [113]:
ls = [x*x for x in range(5)]
arr = np.fromiter(ls, dtype=int)

print("list: ", ls)
print("Array: ", arr)

list:  [0, 1, 4, 9, 16]
Array:  [ 0  1  4  9 16]


In [114]:
np.fromstring("1 2 3 4 5 6 7 8 9", sep=" ", dtype=int)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
ls = list("123456789")
np.array([int(i) for i in ls])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])