In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# head:

custom = pd.read_excel("custom_data.xlsx")
custom.head()

fea1 fea2  fea3   fea4  op
0  abc   a1 -28.0   42.0   1
1  xyz   b1 -32.0   34.0   0
2  pqr   c1  -1.0    NaN   1
3  abc   a1 -37.0  130.0   0
4  ijk   p1 -30.0   92.0   1

In [3]:
# tail:

custom.tail()

fea1 fea2  fea3   fea4  op
245  abc   b1 -37.0  137.0   1
246  ijk   a1 -28.0    NaN   1
247  mno   m1 -28.0   68.0   1
248  abc   b1 -28.0   67.0   1
249  sso   a1 -28.0   10.0   0

In [4]:
# Finding Null values:

custom.isnull().sum()

fea1    47
fea2    16
fea3    31
fea4    16
op       0
dtype: int64

In [5]:
# nrows: (get the no. of rows only)

custom1 = pd.read_excel("custom_data.xlsx", nrows=10)
custom1

fea1 fea2  fea3   fea4  op
0  abc   a1 -28.0   42.0   1
1  xyz   b1 -32.0   34.0   0
2  pqr   c1  -1.0    NaN   1
3  abc   a1 -37.0  130.0   0
4  ijk   p1 -30.0   92.0   1
5  mno   m1 -44.0   10.0   1
6  abc  NaN -34.0   82.0   1
7  sso   y1 -26.0   28.0   1
8  rrp   a1   NaN   80.0   1
9  mno   x1 -37.0   21.0   1

In [6]:
# skiprows:

custom2 = pd.read_excel("custom_data.xlsx", skiprows=[1,2,3,4,5,6,7,8,10])
custom2.head()

fea1 fea2  fea3   fea4  op
0  rrp   a1   NaN   80.0   1
1  qwe   y1 -33.0  129.0   0
2  rsf   p1   8.0  101.0   0
3  abc   m1   NaN   82.0   1
4  pqr   b1  -4.0   40.0   0

In [7]:
# na_values: replace with np.nan

custom = pd.read_excel("custom_data.xlsx", na_values=['NO', 'NAN', 'NA', 'Na', 'no', 'nan'])
custom.head()

fea1 fea2  fea3   fea4  op
0  abc   a1 -28.0   42.0   1
1  xyz   b1 -32.0   34.0   0
2  pqr   c1  -1.0    NaN   1
3  abc   a1 -37.0  130.0   0
4  ijk   p1 -30.0   92.0   1

In [8]:
custom.isnull().sum()

fea1    47
fea2    16
fea3    31
fea4    16
op       0
dtype: int64

In [9]:
# drop column

tra = pd.read_csv("transactions.csv")
tra = tra.drop(columns=['Unnamed: 0'], axis=1)
tra.head(3)

product_code customer_code market_code  order_date  sales_qty  sales_amount  \
0      Prod279        Cus020     Mark011  2017-10-11          1         102.0   
1      Prod279        Cus020     Mark011  2017-10-18          1         102.0   
2      Prod279        Cus020     Mark011  2017-10-19          1         102.0   

  currency  profit_margin_percentage  profit_margin  cost_price  
0      INR                      0.39          39.78       62.22  
1      INR                     -0.12         -12.24      114.24  
2      INR                      0.29          29.58       72.42

In [10]:
tra.shape

(148395, 10)

In [11]:
tra.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148395 entries, 0 to 148394
Data columns (total 10 columns):
 #   Column                    Non-Null Count   Dtype  
---  ------                    --------------   -----  
 0   product_code              148395 non-null  object 
 1   customer_code             148395 non-null  object 
 2   market_code               148395 non-null  object 
 3   order_date                148395 non-null  object 
 4   sales_qty                 148395 non-null  int64  
 5   sales_amount              148395 non-null  float64
 6   currency                  148395 non-null  object 
 7   profit_margin_percentage  148395 non-null  float64
 8   profit_margin             148395 non-null  float64
 9   cost_price                148395 non-null  float64
dtypes: float64(4), int64(1), object(5)
memory usage: 11.3+ MB


In [12]:
# get columns name:

tra.columns

Index(['product_code', 'customer_code', 'market_code', 'order_date',
       'sales_qty', 'sales_amount', 'currency', 'profit_margin_percentage',
       'profit_margin', 'cost_price'],
      dtype='object')

In [13]:
# find data types:

tra.dtypes

product_code                 object
customer_code                object
market_code                  object
order_date                   object
sales_qty                     int64
sales_amount                float64
currency                     object
profit_margin_percentage    float64
profit_margin               float64
cost_price                  float64
dtype: object

In [14]:
# extract object data type:

obj = tra.dtypes[tra.dtypes == "object"]
print(obj, '\n')
print("Object Columns: ", obj.index)

product_code     object
customer_code    object
market_code      object
order_date       object
currency         object
dtype: object 

Object Columns:  Index(['product_code', 'customer_code', 'market_code', 'order_date',
       'currency'],
      dtype='object')


In [15]:
# describe():

tra.describe()

sales_qty  sales_amount  profit_margin_percentage  profit_margin  \
count  148395.000000  1.483950e+05             148395.000000  148395.000000   
mean       16.370376  6.636433e+03                  0.024448     166.158350   
std       115.394269  3.008649e+04                  0.218956    6850.373158   
min         1.000000  5.000000e+00                 -0.350000 -369348.500000   
25%         1.000000  1.760000e+02                 -0.160000     -67.320000   
50%         1.000000  5.190000e+02                  0.020000       5.550000   
75%         7.000000  3.065000e+03                  0.210000     105.600000   
max     14049.000000  1.510944e+06                  0.400000  481775.040000   

         cost_price  
count  1.483950e+05  
mean   6.470649e+03  
std    2.977992e+04  
min    3.050000e+00  
25%    1.665000e+02  
50%    5.082600e+02  
75%    2.907130e+03  
max    1.846742e+06

In [16]:
tra.describe().loc['mean']

sales_qty                     16.370376
sales_amount                6636.432919
profit_margin_percentage       0.024448
profit_margin                166.158350
cost_price                  6470.648570
Name: mean, dtype: float64

In [17]:
# get mean, median, mode (for aparticular neumerical features):

tra['sales_amount'].mean(), tra['sales_amount'].mode(), tra['sales_amount'].std()

(6636.432918898885,
 0    93.0
 dtype: float64,
 30086.491582045244)

In [18]:
# get all object, int & float datatype

obj = tra.dtypes[tra.dtypes == 'object'].index
int64 = tra.dtypes[tra.dtypes == 'int64'].index
float64 = tra.dtypes[tra.dtypes == 'float64'].index

print(obj)
print(int64)
print(float64)

Index(['product_code', 'customer_code', 'market_code', 'order_date',
       'currency'],
      dtype='object')
Index(['sales_qty'], dtype='object')
Index(['sales_amount', 'profit_margin_percentage', 'profit_margin',
       'cost_price'],
      dtype='object')


In [19]:
# Slicing:

tra_head_10 = tra.head(10)
tra_head_10

product_code customer_code market_code  order_date  sales_qty  sales_amount  \
0      Prod279        Cus020     Mark011  2017-10-11          1         102.0   
1      Prod279        Cus020     Mark011  2017-10-18          1         102.0   
2      Prod279        Cus020     Mark011  2017-10-19          1         102.0   
3      Prod279        Cus020     Mark011  2017-11-08          1         102.0   
4      Prod279        Cus020     Mark011  2018-03-09          1         102.0   
5      Prod279        Cus020     Mark011  2018-03-20          1         102.0   
6      Prod279        Cus020     Mark011  2018-03-22          1         102.0   
7      Prod279        Cus020     Mark011  2018-03-23          1         102.0   
8      Prod279        Cus020     Mark011  2018-03-29          1         102.0   
9      Prod279        Cus020     Mark011  2018-04-16          1         102.0   

  currency  profit_margin_percentage  profit_margin  cost_price  
0      INR                      0.39          39.78       62.22  
1      INR                     -0.12         -12.24      114.24  
2      INR                      0.29          29.58       72.42  
3      INR                      0.36          36.72       65.28  
4      INR                     -0.35         -35.70      137.70  
5      INR                      0.26          26.52       75.48  
6      INR                     -0.35         -35.70      137.70  
7      INR                     -0.35         -35.70      137.70  
8      INR                      0.34          34.68       67.32  
9      INR                     -0.06          -6.12      108.12

In [20]:
tra_head_10.iloc[4:7, 2:7]

market_code  order_date  sales_qty  sales_amount currency
4     Mark011  2018-03-09          1         102.0      INR
5     Mark011  2018-03-20          1         102.0      INR
6     Mark011  2018-03-22          1         102.0      INR

In [21]:
# get records bottom to top:

tra_head_10[10:0:-1]

product_code customer_code market_code  order_date  sales_qty  sales_amount  \
9      Prod279        Cus020     Mark011  2018-04-16          1         102.0   
8      Prod279        Cus020     Mark011  2018-03-29          1         102.0   
7      Prod279        Cus020     Mark011  2018-03-23          1         102.0   
6      Prod279        Cus020     Mark011  2018-03-22          1         102.0   
5      Prod279        Cus020     Mark011  2018-03-20          1         102.0   
4      Prod279        Cus020     Mark011  2018-03-09          1         102.0   
3      Prod279        Cus020     Mark011  2017-11-08          1         102.0   
2      Prod279        Cus020     Mark011  2017-10-19          1         102.0   
1      Prod279        Cus020     Mark011  2017-10-18          1         102.0   

  currency  profit_margin_percentage  profit_margin  cost_price  
9      INR                     -0.06          -6.12      108.12  
8      INR                      0.34          34.68       67.32  
7      INR                     -0.35         -35.70      137.70  
6      INR                     -0.35         -35.70      137.70  
5      INR                      0.26          26.52       75.48  
4      INR                     -0.35         -35.70      137.70  
3      INR                      0.36          36.72       65.28  
2      INR                      0.29          29.58       72.42  
1      INR                     -0.12         -12.24      114.24

In [22]:
# sorted order:
sorted(tra_head_10)

['cost_price',
 'currency',
 'customer_code',
 'market_code',
 'order_date',
 'product_code',
 'profit_margin',
 'profit_margin_percentage',
 'sales_amount',
 'sales_qty']

In [23]:
tra_head_10[sorted(tra_head_10)]

cost_price currency customer_code market_code  order_date product_code  \
0       62.22      INR        Cus020     Mark011  2017-10-11      Prod279   
1      114.24      INR        Cus020     Mark011  2017-10-18      Prod279   
2       72.42      INR        Cus020     Mark011  2017-10-19      Prod279   
3       65.28      INR        Cus020     Mark011  2017-11-08      Prod279   
4      137.70      INR        Cus020     Mark011  2018-03-09      Prod279   
5       75.48      INR        Cus020     Mark011  2018-03-20      Prod279   
6      137.70      INR        Cus020     Mark011  2018-03-22      Prod279   
7      137.70      INR        Cus020     Mark011  2018-03-23      Prod279   
8       67.32      INR        Cus020     Mark011  2018-03-29      Prod279   
9      108.12      INR        Cus020     Mark011  2018-04-16      Prod279   

   profit_margin  profit_margin_percentage  sales_amount  sales_qty  
0          39.78                      0.39         102.0          1  
1         -12.24                     -0.12         102.0          1  
2          29.58                      0.29         102.0          1  
3          36.72                      0.36         102.0          1  
4         -35.70                     -0.35         102.0          1  
5          26.52                      0.26         102.0          1  
6         -35.70                     -0.35         102.0          1  
7         -35.70                     -0.35         102.0          1  
8          34.68                      0.34         102.0          1  
9          -6.12                     -0.06         102.0          1

In [24]:
# sort values:

tra_head_10[['cost_price', 'sales_amount']].sort_values

<bound method DataFrame.sort_values of    cost_price  sales_amount
0       62.22         102.0
1      114.24         102.0
2       72.42         102.0
3       65.28         102.0
4      137.70         102.0
5       75.48         102.0
6      137.70         102.0
7      137.70         102.0
8       67.32         102.0
9      108.12         102.0>

In [25]:
# getting unique values:

for col in tra:
    print(f"{col}:   {len(tra[col].unique())} unique values")

product_code:   338 unique values
customer_code:   38 unique values
market_code:   15 unique values
order_date:   804 unique values
sales_qty:   564 unique values
sales_amount:   7981 unique values
currency:   2 unique values
profit_margin_percentage:   76 unique values
profit_margin:   51336 unique values
cost_price:   57024 unique values


In [26]:
# np.where(): Finding Null values.

fea1_ind = np.where(custom['fea1'].isnull() == True)
fea2_ind = np.where(custom['fea2'].isnull() == True)
fea3_ind = np.where(custom['fea3'].isnull() == True)
fea4_ind = np.where(custom['fea4'].isnull() == True)

In [27]:
print("fea1: \n", fea1_ind, '\n')
print("fea2: \n", fea2_ind, '\n')
print("fea3: \n", fea3_ind, '\n')
print("fea4: \n", fea4_ind)

fea1: 
 (array([ 15,  31,  32,  33,  34,  35,  51,  52,  53,  54,  57,  70,  71,
        72,  73,  79,  87,  90,  92,  93, 100, 110, 113, 114, 115, 117,
       120, 124, 131, 140, 143, 145, 146, 152, 164, 171, 172, 173, 185,
       199, 203, 204, 205, 212, 221, 234, 242], dtype=int64),) 

fea2: 
 (array([  6,  23,  41,  59,  74,  89, 104, 119, 134, 137, 149, 164, 179,
       191, 206, 224], dtype=int64),) 

fea3: 
 (array([  8,  12,  24,  39,  51,  66,  81,  96, 114, 132, 150, 164, 165,
       166, 167, 168, 169, 170, 171, 172, 184, 185, 205, 206, 218, 219,
       220, 221, 222, 223, 235], dtype=int64),) 

fea4: 
 (array([  2,  24,  45,  66,  84, 105, 126, 144, 156, 168, 187, 208, 220,
       225, 233, 246], dtype=int64),)


In [28]:
# get the data where missing values is present:

custom.iloc[fea1_ind].head()

fea1 fea2  fea3   fea4  op
15  NaN   b1 -28.0  147.0   1
31  NaN   b1   6.0   30.0   1
32  NaN   c1 -41.0   24.0   1
33  NaN   a1   0.0   70.0   1
34  NaN   p1 -36.0   13.0   1

In [29]:
# groupby operation:

tra.groupby('market_code').sum('sales_amount')

sales_qty  sales_amount  profit_margin_percentage  profit_margin  \
market_code                                                                     
Mark001          50485    18042702.0                     22.85      300573.00   
Mark002         383643   150084801.0                    270.05     4872639.77   
Mark003         206925   132307441.0                    495.70     2848268.51   
Mark004         988294   519514271.0                   1035.51    11953798.52   
Mark005          16642    13582609.0                     67.66      -65878.45   
Mark006            413      373115.0                     -0.04      -77534.96   
Mark007          86884    42084571.0                    329.87     1040750.53   
Mark008          37092     3094007.0                      1.32       31161.21   
Mark009           5505     4428393.0                      9.42      182260.78   
Mark010         255482    18813466.0                    122.99      703289.99   
Mark011         262094    55026321.0                   1204.34     1412109.72   
Mark012          17099     2605796.0                     10.92      126677.05   
Mark013          25856    16525290.0                      5.64     1246399.16   
Mark014          77889     7436823.0                     50.82       46957.22   
Mark015          14979      893857.0                      0.86       35596.36   

               cost_price  
market_code                
Mark001      1.774213e+07  
Mark002      1.452122e+08  
Mark003      1.294592e+08  
Mark004      5.076160e+08  
Mark005      1.364849e+07  
Mark006      4.506500e+05  
Mark007      4.104382e+07  
Mark008      3.062846e+06  
Mark009      4.246132e+06  
Mark010      1.811018e+07  
Mark011      5.361421e+07  
Mark012      2.479119e+06  
Mark013      1.527889e+07  
Mark014      7.389866e+06  
Mark015      8.582606e+05

In [30]:
tra.columns

Index(['product_code', 'customer_code', 'market_code', 'order_date',
       'sales_qty', 'sales_amount', 'currency', 'profit_margin_percentage',
       'profit_margin', 'cost_price'],
      dtype='object')

In [31]:
# map:

custom['op'] = custom['op'].map({0:False, 1:True})
custom.head()

fea1 fea2  fea3   fea4     op
0  abc   a1 -28.0   42.0   True
1  xyz   b1 -32.0   34.0  False
2  pqr   c1  -1.0    NaN   True
3  abc   a1 -37.0  130.0  False
4  ijk   p1 -30.0   92.0   True

In [32]:
# drop_duplicates:

custom = custom.drop_duplicates()
custom.shape

(250, 5)

In [34]:
# Rename columns:

custom = custom.rename({'fea1': 'F1', 'fea2': 'F2', 'fea3':'F3', 'fea4':'F4', 'op': 'Output'}, axis=1)
custom.head()

F1  F2    F3     F4  Output
0  abc  a1 -28.0   42.0    True
1  xyz  b1 -32.0   34.0   False
2  pqr  c1  -1.0    NaN    True
3  abc  a1 -37.0  130.0   False
4  ijk  p1 -30.0   92.0    True

In [35]:
custom.columns

Index(['F1', 'F2', 'F3', 'F4', 'Output'], dtype='object')

In [36]:
# astype:

custom['F5'] = custom['F1'] + custom['F4'].astype(str)
custom.head()

F1  F2    F3     F4  Output        F5
0  abc  a1 -28.0   42.0    True   abc42.0
1  xyz  b1 -32.0   34.0   False   xyz34.0
2  pqr  c1  -1.0    NaN    True    pqrnan
3  abc  a1 -37.0  130.0   False  abc130.0
4  ijk  p1 -30.0   92.0    True   ijk92.0